---
name: Daily Build (RPi)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Rasperry Pi Image
    runs-on: ubuntu-latest

    steps:
      # - name: Clean
      #   uses: easimon/maximize-build-space@v7
      #   with:
      #     root-reserve-mb: 16000
      #     swap-size-mb: 1024
      #     remove-dotnet: "true"
      #     remove-android: "true"
      #     remove-haskell: "true"
      #     remove-codeql: "true"
      #     remove-docker-images: "true"
      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y golang git libglib2.0-dev libostree-dev qemu-system-x86 \
          qemu-user-static debootstrap systemd-container
      - name: Checkout debos
        uses: actions/checkout@v3
        with:
          repository: go-debos/debos
          path: debos
      - name: Install debos
        run: |
          cd debos
          go get github.com/go-debos/fakemachine@f70ae41
          sudo GOPATH=${{ env.GOPATH }} go install ./cmd/debos
        env:
          GOPATH: /opt/src/gocode
      - uses: actions/checkout@v3
      - name: Build
        run: |
          sudo /opt/src/gocode/bin/debos base-arm64.go.yml
          sudo /opt/src/gocode/bin/debos rpi.go.yml
